<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function loadUserByUsername($username,$password)
    {	//echo "===".$username."=====".$password;exit;
        $data = $this->createQueryBuilder('u')
            ->where('u.username = :username And u.password = :password')
            ->setParameter('username', $username)
            ->setParameter('password', $password)
            ->getQuery()
            ->getOneOrNullResult();
            print_r($data);exit("===");
  //   		$em = $this->get('doctrine')->getManager();
  //           $query = $em->createQuery(
  //  					'SELECT u.username ,u.password
  //  					FROM AdminBundle:User u
  //   					WHERE u.username = :username And u.password = :password'
		// 			)->setParameter('username', $username)
  //           		->setParameter('password', $password);

		// $products = $query->getResult();
		return $data;
    }
}
